class_name FI

const POINT_ONE = 6553
const POINT_TWO = 6553 * 2
const POINT_THREE = 6553 * 3
const POINT_FOUR = 6553 * 4
const POINT_FIVE = 6553 * 5
const POINT_SIX = 6553 * 6
const POINT_SEVEN = 6553 * 7
const POINT_EIGHT = 6553 * 8
const POINT_NINE = 6553 * 9
const ONE = 65536
const ONE_POINT_ONE = ONE + POINT_ONE
const ONE_POINT_TWO = ONE + POINT_TWO
const ONE_POINT_THREE = ONE + POINT_THREE
const ONE_POINT_FOUR = ONE + POINT_FOUR
const ONE_POINT_FIVE = ONE + POINT_FIVE
const ONE_POINT_SIX = ONE + POINT_SIX
const ONE_POINT_SEVEN = ONE + POINT_SEVEN
const ONE_POINT_EIGHT = ONE + POINT_EIGHT
const ONE_POINT_NINE = ONE + POINT_NINE
const TWO = ONE * 2
